spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          env:
          - name: FABRIC8_K8S_SECRETS_PATH
            value: /etc/secrets
          volumeMounts:
          - name: servicenow-secret-volume
            mountPath: /etc/secrets/servicenow
            readOnly: true  
      volumes:
        - name: servicenow-secret-volume
          secret:
            secretName: servicenow